### PR TITLE
#3: fix skinnable (closes #3)

### LINKED ISSUE #3: fix skinnable
## description
remove locals caching strategy

### PR DESCRIPTION
**Pull request by francescogior**
Closes #3

## Test Plan
tested on brc

### CODE REVIEW

File: src/skinnable.js [hunk 1]
```diff
@@ -1,7 +1,6 @@
 import t from 'tcomb';
 import omit from 'lodash/omit';
```
Comment (FrancescoCioria) [inline src/skinnable.js]: wait, `omit` is not used :)
